ptlteste/ptlteste/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [


    path('admin/', admin.site.urls),
    path('api-auth/',include('rest_framework.urls')),
    path('', include('usuarios.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('social_django.urls')),

]

ptlteste/usuarios/urls.py
from django.urls import path, include
from rest_framework import routers
from .views import gerar_token, UsuarioViewSet,do_login, do_logout, index, editar,CadastrarUserView, cadastrar, search_by_cep
from django.conf.urls import url, include
from rest_framework import permissions, authentication
from rest_framework_jwt.views import obtain_jwt_token

app_name = 'usuarios'


router = routers.DefaultRouter()
router.register(r'usuarios', UsuarioViewSet)

urlpatterns = [

    path('index/', index , name="index"),
    path('', index , name="index"),
    path('editar/<pk>', editar , name="editar"),
    path('cadastrar/',cadastrar  , name="cadastrar"), #templeate
    path('api_cadastrar/', CadastrarUserView.as_view() , name="api_cadastrar"), #endpoint

    path('api/', include(router.urls)),
    path('gerar_token/', gerar_token, name = "gerar_token"),
    path('accounts/login/', do_login, name = "login"),
    path('logout/', do_logout, name = "logout"),
    path('accounts/', include('django.contrib.auth.urls')),

    # cep
    path('dadoscep/', search_by_cep, name = "dadoscep"),

]

ptlteste/usuarios/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager
from django.core import validators
from django.utils.translation import ugettext_lazy as _
import re
from django.utils import timezone
import datetime


class UserManager(BaseUserManager):

    def _create_user(self, username, email, password, is_staff, is_superuser, **extra_fields):
        now = timezone.now()
        if not username:
            raise ValueError(_('O nome do usuário deve ser informado'))
        email = self.normalize_email(email)
        user = self.model(username=username, email=email, is_staff=is_staff, is_active=True, is_superuser=is_superuser, last_login=now, date_joined=now, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, username, email=None, password=None, **extra_fields):
        return self._create_user(username, email, password, False, False, **extra_fields)

    def create_superuser(self, username, email, password, **extra_fields):
        user=self._create_user(username, email, password, True, True, **extra_fields)
        user.is_active=True
        user.save(using=self._db)
        return user



class Usuario(AbstractBaseUser, PermissionsMixin):

    username = models.CharField(_('username'), max_length=15, unique=True, help_text=_('Required. 15 characters or fewer. Letters, numbers and @/./+/-/_ characters'), validators=[ validators.RegexValidator(re.compile('^[\w.@+-]+$'), _('Enter a valid username.'), _('invalid'))])
    first_name = models.CharField(_('first name'), max_length=30)
    last_name = models.CharField(_('last name'), max_length=30)
    email = models.EmailField(_('email address'), max_length=255, unique=True)
    is_staff = models.BooleanField(_('staff status'), default=False, help_text=_('Designates whether the user can log into this admin site.'))
    is_active = models.BooleanField(_('active'), default=True, help_text=_('Designates whether this user should be treated as active. Unselect this instead of deleting accounts.'))
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)
    cpf= models.CharField(max_length=11,null=False,blank=False)
    pis= models.CharField(max_length=11,null=False,blank=False)
    cep = models.CharField(max_length=150,null=False,blank=False)
    rua = models.CharField(max_length=150,null=False,blank=False)
    numero = models.CharField(max_length=20,null=False,blank=False)
    complemento = models.CharField(max_length=150,null=False,blank=False)
    municipio = models.CharField(max_length=150,null=False,blank=False)
    estado = models.CharField(max_length=2,null=False,blank=False)
    pais = models.CharField(max_length=50,null=False,blank=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'first_name', 'last_name']

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def get_full_name(self):
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def authenticate(username=None, password=None, **kwargs):
        UserModel = get_user_model()
        try:
            user = UserModel.objects.get(email=username)
        except UserModel.DoesNotExist:
            try:
                user = UserModel.objects.get(cpf=username)
            except  UserModel.DoesNotExist:
                try:
                    user = UserModel.objects.get(pis=username)
                except  UserModel.DoesNotExist:
                    return None
                else:
                    if user.check_password(password):
                        return user
                return None
            else:
                if user.check_password(password):
                    return user
            return None
        else:
            if user.check_password(password):
                return user
        return None


    def __str__(self):
       return  self.first_name

    objects = UserManager()

ptlteste/usuarios/views.py
from rest_framework import viewsets, permissions, authentication, filters
from .models import Usuario
from .serializers import UsuarioSerializer
from django.views.decorators.csrf import csrf_exempt
from rest_framework_jwt.settings import api_settings
from rest_framework.decorators import action
from rest_framework.generics import UpdateAPIView
from rest_framework.views import APIView
from rest_framework.parsers import MultiPartParser
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated
from rest_framework.authentication import TokenAuthentication
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
import json
import os
from django.conf import settings
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
import requests

jwt_payload_handler = api_settings.JWT_PAYLOAD_HANDLER
jwt_encode_handler = api_settings.JWT_ENCODE_HANDLER

# MANIPULAÇÃO DOS USUARIOS
class UsuarioViewSet(viewsets.ModelViewSet):
    queryset = Usuario.objects.all()
    serializer_class = UsuarioSerializer


#PARA CRIAÇÃO DE USUÁRIO
class CadastrarUserView(APIView):
    parser_class = [MultiPartParser]

    def post(self, request, *args, **kwargs):
        retorno = json.loads(self.request.body.decode("utf-8"))

        username = retorno.get('username')
        first_name = retorno.get('first_name')
        last_name = retorno.get('last_name')
        email = retorno.get('email')
        cep = retorno.get('cep')
        rua = retorno.get('rua')
        numero = retorno.get('numero')
        complemento = retorno.get('complemento')
        municipio = retorno.get('municipio')
        estado = retorno.get('estado')
        pais = retorno.get('pais')
        cpf = retorno.get('cpf')
        pis = retorno.get('pis')
        password = retorno.get('password')
        is_superuser = retorno.get('is_superuser')
        is_active = retorno.get('is_active')

        user = Usuario.objects.create_user(username, email, password)

        user.first_name = first_name
        user.last_name = last_name
        user.email = email
        user.cep = cep
        user.rua = rua
        user.numero = numero
        user.complemento = complemento
        user.municipio = municipio
        user.estado = estado
        user.pais = pais
        user.cpf = cpf
        user.pis = pis
        user.is_superuser = is_superuser
        user.is_active = is_active
        user.save()

        msg = 'Cadastro realizado!'

        return Response({'status': msg})


@csrf_exempt
def gerar_token(request):
    msg =''
    dicToken={}
    usuario=  Usuario.objects.all()
    if request.method == 'POST':
        email_cpf_pis = request.POST.get('email')
        password = request.POST.get('password')
        payload = jwt_payload_handler(usuario)
        token = jwt_encode_handler(payload)


        dicToken.update({'Token':token})

    return   HttpResponse(json.dumps(dicToken), content_type='application/json')



def do_login(request):
    msg=''
    dicToken={}
    if request.method == 'POST':
        email = request.POST.get('email')
        password =request.POST.get('password')
        user = Usuario.authenticate(username=email, password=password)
        if user is not None:
            usuario = Usuario.objects.get(id=user.id)
            login(request, user,  backend='django.contrib.auth.backends.ModelBackend')
            payload = jwt_payload_handler(usuario)
            token = jwt_encode_handler(payload)
            dicToken.update({'token':token})
            return render(request,'usuarios/index.html',{'token': dicToken } )
        else:
            msg = 'Usuário ou senha inválidos!'

    return render(request,'registration/login.html',{'msg': msg} )

def do_logout(request):
    logout(request)
    return redirect('/login/auth0')


def index(request):

    return render(request, 'usuarios/index.html')

def editar(request,pk):

    return render(request, 'usuarios/editar.html',{'id':pk})


def cadastrar(request):

    return render(request, 'usuarios/cadastrar.html')



@csrf_exempt
def search_by_cep(request):
    cep = request.POST.get('cep')
    #print('vai printar')
    #print(cep.replace('"','').replace('.','').replace('-',''))
    #token = "ab56b218a8cdc76afda4c63286655086"
    #headers = {'Authorization': 'Token token=%s' % token}
    url = "https://viacep.com.br/ws/"+format(cep.replace('"','').replace('.','').replace('-',''))+"/json/"
    response = requests.get(url)
    #print(response.json())
    return  JsonResponse({"data":response.json()})

ptlteste/usuarios/templates/usuarios/cadastrar.html
<html lang="en">
<head>
  <title>Teste PTL</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <script src="https://kit.fontawesome.com/55c68eb07d.js" crossorigin="anonymous"></script>

</head>
<body>


<div class="container">
  <h1>Cadastro de usuário</h1>
<form>
    {% csrf_token %}
  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="nome">Nome</label>
      <input type="text" class="form-control" id="nome" placeholder="Nome" required autofocus>
    </div>
    <div class="form-group col-md-6">
      <label for="sobrenome">Sobrenome</label>
      <input type="text" class="form-control" id="sobrenome" placeholder="Sobrenome" required >
    </div>
  </div>
  <div class="form-group">
    <div class="form-group col-md-12">
      <label for="email">E-mail</label>
      <input type="email" class="form-control" id="email" placeholder="E-mail" required>
    </div>
  </div>
  <div class="form-group">
    <div class="form-group col-md-12">
      <label for="cep">CEP</label>
      <input type="text" onchange="BuscaEndereco()" class="form-control" id="cep" placeholder="cep" required>
    </div>
  </div>
  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="rua">Rua</label>
      <input type="text" class="form-control" id="rua" required>
    </div>
    <div class="form-group col-md-2">
      <label for="numero">Número</label>
      <input type="text" class="form-control" id="numero" required>
    </div>
    <div class="form-group col-md-4">
      <label for="complemento">Complemento</label>
      <input type="text" class="form-control" id="complemento" required>
    </div>
  </div>
  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="municipio">Município</label>
      <input type="text" class="form-control" id="municipio" required>
    </div>
    <div class="form-group col-md-2">
      <label for="estado">Estado</label>
      <input type="text" class="form-control" id="estado" required>
    </div>
    <div class="form-group col-md-4">
      <label for="pais">País</label>
      <input type="text" class="form-control" id="pais" required>
    </div>
  </div>
  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="cpf">CPF</label>
      <input type="text" class="form-control" id="cpf" required>
    </div>
    <div class="form-group col-md-6">
      <label for="pis">PIS</label>
      <input type="text" class="form-control" id="pis" required>
    </div>
  </div>
  <div class="form-row">
    <div class="form-group col-md-12">
      <label for="senha">Senha</label>
      <input type="text" class="form-control" id="senha" required>
    </div>

  </div>

  <div class="form-row">
    <div class="form-group col-md-12">
        <button onclick="SalvarCadastro()" class="btn btn-primary">Salvar</button>
        <a href="{% url 'usuarios:login'  %}" class="btn btn-danger">Voltar</a>
    </div>
  </div>

</form>
<div>



<script>



  function SalvarCadastro() {

                var nome= document.getElementById('nome').value;
                var sobrenome= document.getElementById('sobrenome').value;
                var email= document.getElementById('email').value;
                var cep= document.getElementById('cep').value;
                var rua= document.getElementById('rua').value;
                var numero= document.getElementById('numero').value;
                var complemento= document.getElementById('complemento').value;
                var municipio= document.getElementById('municipio').value;
                var estado= document.getElementById('estado').value;
                var pais= document.getElementById('pais').value;
                var cpf= document.getElementById('cpf').value;
                var pis= document.getElementById('pis').value;
                var senha= document.getElementById('senha').value;

                if (ValidarCPF(cpf)==false){
                  alert('CPF inválido!')
                  document.getElementById('cpf').focus();
                }else  if (nome == ''){
                  alert('Informe o nome');
                  document.getElementById('nome').focus();
                } else if (sobrenome =='0') {
                  alert('Informe a sobrenome');
                  document.getElementById('sobrenome').focus();
                } else if (email =='') {
                  alert('Informe o email');
                  document.getElementById('email').focus();
                } else if (cep =='') {
                  alert('Informe o cep');
                  document.getElementById('cep').focus();
                } else if (rua =='') {
                  alert('Informe a rua');
                  document.getElementById('rua').focus();
                } else if (numero =='') {
                  alert('Informe o numero');
                  document.getElementById('numero').focus();
                } else if (complemento =='') {
                  alert('Informe o complemento');
                  document.getElementById('complemento').focus();
                } else if (municipio =='') {
                  alert('Informe o municipio');
                  document.getElementById('municipio').focus();
                } else if (estado =='') {
                  alert('Informe o estado');
                  document.getElementById('estado').focus();
                } else if (pais =='') {
                  alert('Informe o pais');
                  document.getElementById('pais').focus();
                } else if (pis =='') {
                  alert('Informe o pis');
                  document.getElementById('pis').focus();
                } else{

                const url = '{% url "usuarios:api_cadastrar" %}'
                const body = { username:nome,
                'first_name': nome,
                'last_name': sobrenome,
                'email': email,
                'cep': cep,
                'rua': rua,
                'numero':numero,
                'complemento':complemento,
                'municipio':municipio,
                'estado':estado,
                'pais':pais,
                'cpf':cpf,
                'pis':pis,
                'password': senha,
                'is_superuser':true,
                'is_active':true
                 }

                  fetch(url, {
                  headers: { "Content-Type": "application/json; charset=UTF-8","X-CSRFToken": '{{csrf_token}}' },
                  method: 'POST',
                  body: JSON.stringify(body)
                  })
                .then((res) => res.json() )
                .then((response) =>  resultado(response))

                 function resultado(response) {
                    alert(response.status);
                 }
               }
}


        function ValidarCPF(strCPF) {
                  var Soma;
                  var Resto;
                  Soma = 0;
                if (strCPF == "00000000000") return false;

                for (i=1; i<=9; i++) Soma = Soma + parseInt(strCPF.substring(i-1, i)) * (11 - i);
                Resto = (Soma * 10) % 11;

                  if ((Resto == 10) || (Resto == 11))  Resto = 0;
                  if (Resto != parseInt(strCPF.substring(9, 10)) ) return false;

                Soma = 0;
                  for (i = 1; i <= 10; i++) Soma = Soma + parseInt(strCPF.substring(i-1, i)) * (12 - i);
                  Resto = (Soma * 10) % 11;

                  if ((Resto == 10) || (Resto == 11))  Resto = 0;
                  if (Resto != parseInt(strCPF.substring(10, 11) ) ) return false;
                  return true;
              }

              $("#cep").blur(function() {

                                  var cep = $(this).val();

                                              $.ajax({
                                                      url :'{% url "usuarios:dadoscep" %}' ,
                                                      type : 'POST',
                                                      data: 'cep=' + cep,
                                                      dataType: 'json',
                                                      success: function(data){
                                                          if(data){

                                                              var cidade = JSON.stringify(data.data.localidade);
                                                              var bairro = JSON.stringify(data.data.bairro);
                                                              var rua = JSON.stringify(data.data.logradouro);
                                                              var estado = JSON.stringify(data.data.uf);
                                                              var complemento = JSON.stringify(data.data.complemento);

                                                              $("#municipio").val(cidade.replace(/['"]+/g, ''));
                                                              $("#bairro").val(bairro.replace(/['"]+/g, ''));
                                                              $("#rua").val(rua.replace(/['"]+/g, ''));
                                                              $("#estado").val(estado.replace(/['"]+/g, ''));
                                                              $("#complemento").val(complemento.replace(/['"]+/g, ''));

                                                          }
                                                      },
                                                  });
                                  });




</script>

</body>
</html>

ptlteste/usuarios/templates/usuarios/index.html
<!-- Estendemos do template base -->
{% extends "layouts/base.html" %}

<!-- Bloco que define o <title></title> da nossa página -->
{% block title %}TESTE - Home{% endblock %}
{% load static %}

<!-- Bloco de conteúdo da nossa página -->
{% block conteudo %}
<div class="input-group">
  <div class="col-md-10">
    <h1>Olá! {{ user.get_full_name }}.</h1>
  </div>
  <div class="col-md-2">
    <span class="input-group-btn">
      <a class="btn btn-primary" href="{% url 'usuarios:editar' pk=user.id %}" style="margin-top: 20%;"  role="button"><i class="fas fa-user-edit fa-2x"></i></a>
    </span>
  </div>
</div>

{% endblock %}



{% block scripts %}

<script>

{% for k,v in token.items %}

  var token= '{{v}}'

{% endfor %}


window.localStorage.setItem('token', token);
</script>

{% endblock %}